/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.kawaii.ventas.views.ventas;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.kawaii.ventas.controllers.VentaController;
import pe.kawaii.ventas.models.Venta;

/**
 *
 * @author Ivan
 */
public class PanelMantenimientoVenta extends javax.swing.JPanel {

    private ArrayList<Venta> ventas;
    private Venta ventaSeleccionada;

    /**
     * Creates new form PanelMantenimientoVentas
     */
    public PanelMantenimientoVenta() {
        ventas = new ArrayList<>();
        initComponents();
        actualizarTablaVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnAnular = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mantenimiento de ventas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnular)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        int rowIndex = this.tblVentas.getSelectedRow();
        this.ventaSeleccionada = this.ventas.get(rowIndex);
    }//GEN-LAST:event_tblVentasMouseClicked

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        int rowIndex = this.tblVentas.getSelectedRow();

        if (rowIndex != -1) {
            int id = this.ventas.get(rowIndex).getId();
            VentaController.anularVenta(id);
            actualizarTablaVentas();
            JOptionPane.showMessageDialog(null, "El venta a ha anulado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);        
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    void actualizarTablaVentas() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Optional<ArrayList<Venta>> ventasObtenidas = VentaController.findAll();

        if (ventasObtenidas.isPresent()) {
            this.ventas = ventasObtenidas.get();

            DefaultTableModel dtm = new DefaultTableModel(0, 0);
            String header[] = new String[]{"ID", "Vendedor ID", "Vendedor", "Cliente ID", "Nombre del cliente", "Fecha", "Total", "Anulada"};
            dtm.setColumnIdentifiers(header);
            this.tblVentas.setModel(dtm);

            for (Venta v : ventas) {
                dtm.addRow(new Object[]{
                    v.getId(),
                    v.getVendedor().getId(),
                    v.getVendedor().getUsername(),
                    v.getCliente().getId(),
                    v.getCliente().getNombreCompleto(),
                    format.format(v.getFechaRegistro()),
                    v.getTotal(),
                    (v.isAnulada()) ? "Sí" : "No"
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
